# Generated by Django 5.2.1 on 2025-06-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
